openapi: 3.0.3
info:
  title: Short URL Service API
  description: URL SHORTENER API
  termsOfService: /terms-of-use/
  contact:
    email: user@gmail.com
  version: v1
tags:
- name: URL
  description: Url shorten endpoints
  externalDocs:
    description: Find out more
servers:
- url: http://localhost:3000/api
  description: Local server
- url: ''
  description: Production server
paths:
  /shorten:
    post:
      tags:
      - URL
      summary: Create a new short URL
      description: "This endpoint allows the user to create a new short URL by providing a long URL, \nan optional custom short URL, and an expiration date.\n"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  description: The long URL to be shortened
                expiredAt:
                  type: string
                  format: date-time
                  description: The optional expiration date for the short URL
                customShortUrl:
                  type: string
                  description: Optional custom short URL
      responses:
        '201':
          description: Short URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  shortUrl:
                    type: string
                  securityCode:
                    type: string
        '400':
          description: Custom short URL is already in use
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /edit:
    put:
      tags:
      - URL
      summary: Edit a short URL
      description: "This endpoint allows the user to edit a short URL by providing the short URL, \na security code, and the new long URL or expiration date.\n"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shortUrl:
                  type: string
                  description: The short URL to be edited
                securityCode:
                  type: string
                  description: The security code to authorize the request
                longUrl:
                  type: string
                  description: The new long URL (optional)
                expiredAt:
                  type: string
                  format: date-time
                  description: The new expiration date (optional)
      responses:
        '200':
          description: Short URL edited successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized (wrong security code)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /deactivate:
    put:
      tags:
      - URL
      summary: Deactivate a short URL
      description: "This endpoint allows the user to deactivate a short URL by providing the short URL \nand a security code.\n"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shortUrl:
                  type: string
                  description: The short URL to be deactivated
                securityCode:
                  type: string
                  description: The security code to authorize the request
      responses:
        '200':
          description: Short URL deactivated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized (wrong security code)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /{shortUrl}:
    get:
      tags:
      - URL
      summary: Redirect a short URL
      description: |
        This endpoint allows the user to redirect a short URL to the associated long URL.
      parameters:
      - in: path
        name: shortUrl
        required: true
        schema:
          type: string
          description: The short URL to be redirected
      responses:
        '200':
          description: Successfully redirected to the long URL
          content:
            text/html: {}
        '404':
          description: URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '410':
          description: URL is deactivated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
